#!/bin/bash -x

PID_FILE="$OPENSHIFT_DATA_DIR"/puma.pid

if [ -f "$PID_FILE" ]; then
  PID=$(<"$OPENSHIFT_DATA_DIR"/puma.pid)
  if [[ "$PID" ]]; then
    kill "$PID" || :
  fi

  sleep 5

  kill -9 "$PID" || :

  rm -f "$PID_FILE"
fi

exit 0
